### ISSUE TITLE
The editor blinks in Chrome when scroll the page

### ISSUE THREAD

**Issue by dongli** [froala/wysiwyg-editor#1252]
As the title says, when I browsing https://www.froala.com/wysiwyg-editor, scroll the page right when the top of the editor touch the window top, the editor becomes blinking!! The version of Chrome is 52.0.2729.3 dev (64-bit).

![2016-05-11 10 47 45](https://cloud.githubusercontent.com/assets/367959/15185155/84cb5644-17ca-11e6-9fd4-23e40f1eacd7.png)
![2016-05-11 10 47 55](https://cloud.githubusercontent.com/assets/367959/15185161/89bca7b6-17ca-11e6-9469-25a99e8da24d.png)
![2016-05-11 10 48 08](https://cloud.githubusercontent.com/assets/367959/15185168/8e6040a2-17ca-11e6-885b-4df2090fa708.png)

**Comment by stefanneculai** [comment]
It's fixed on master.

**Comment by hardikrazoo** [comment]
It's still showing the same issue of blinking on scroll on master so can you specify in which version of froala it's fixed? Please provide proper solution.

**Comment by stefanneculai** [comment]
@hardikrazoo this was fixed in V2.3.0.

**Comment by hardikrazoo** [comment]
It's also not working on V2.3.0. Please review it. The issue is still there

**Comment by stefanneculai** [comment]
@hardikrazoo Are you able to reproduce it on our website?

**Comment by igorrynkovoy** [comment]
Have the same issue.
