### ISSUE TITLE
Iframe height is not updated

### ISSUE THREAD

**Issue by Vaultman** [froala/wysiwyg-editor#1489]
##### Expected behavior.
Iframe height should automatically update based on content height

##### Actual behavior.
when using `iframe: true` together with `iframeStyleFiles: ['my/css/file.css']`, iframe height is not updated.

##### OS.
OSX 10.11

##### Browser.
All of them

**Comment by stefanneculai** [comment]
It has been fixed on the master branch few days ago.

**Comment by Vaultman** [comment]
I know, but it is still not working. Using latest master from github. 

![](http://g.recordit.co/p2abaO6Vqg.gif)

**Comment by stefanneculai** [comment]
Could you please make a jsFiddle?

**Comment by Vaultman** [comment]
Sure https://jsfiddle.net/4jfqszej/1/

**Comment by stefanneculai** [comment]
@Vaultman the problem appears to come from your `height: 100%` property set in the external CSS for body and height.
