### ISSUE TITLE
tool bar is not show. inline mode.

### ISSUE THREAD

**Issue by poliaca** [froala/wysiwyg-editor#1604]
##### Expected behavior.
The tool bar should be displayed even if there are double-byte characters.

##### Actual behavior.
tool bar is not show.

##### Steps to reproduce the problem.
toolbarInline: true
input double-byte characters.

##### OS.
Windows7

##### Browser.
Chrome 54.0.2840.87

**Comment by stefanneculai** [comment]
Are you able to reproduce it on our website? https://www.froala.com/wysiwyg-editor/inline

**Comment by poliaca** [comment]
Yes.
Reproduce it by inputting Japanese.

**Comment by poliaca** [comment]
Javanese sample.

あいうえお

**Comment by stefanneculai** [comment]
Could you please let us know the exact steps to reproduce it? Letting us know step by step what keys you press on the QUERTY keyboard would be very helpful. Thank you.

**Comment by poliaca** [comment]
It seems that sample text is not reproduced by copy & paste.
Any key can be used as long as you can input Japanese.
For example, you can use only the key "A".
A corresponds to "あ".

**Comment by stefanneculai** [comment]
It should be fixed on master now.

**Comment by ceruberu** [comment]
I have same problem but in Korean.
If I type anything in Korean, inline toolbar does not show until I press enter. (clicking other places does not solve this problem)
I can reproduce this in [your example](https://www.froala.com/wysiwyg-editor/examples/inline)
