### ISSUE TITLE
Cmd+A vs cursor selection applyStyle yields different results

### ISSUE THREAD

**Issue by GMiLL5** [froala/wysiwyg-editor#1726]
##### Expected behavior.
Consistent behaviour when applying styles to nested lists when using cmd+a vs cursor selection

##### Actual behavior.
Using cmd+a vs selecting with your cursor yields different results from applyStyle

###### 1. Cursor selection:
1. Add a list to the editor
2. Add a nested list
3. Select through the entire list
4. Change the text color

###### 2. Cmd+a
1. Add a list to the editor
2. Add a nested list
3. Cmd+a to select entire editor contents (including list)
4. Change the text color

In 1 you'll see the color apply as expected. In 2 the nested list bullets change to match the applied style.

##### OS.
Any

##### Browser.
Any

**Comment by GMiLL5** [comment]
Instead of creating a new ticket, here's an example of behaviour that arises from this bug (using the editor at froala.com)

When the list items are being added above the nested list, I'm pressing enter where you can see the cursor.

I also press backspace several times but it has no effect

![bug](https://cloud.githubusercontent.com/assets/1800407/22476909/6c2411c4-e7ba-11e6-8a60-66e7982ac486.gif)

**Comment by GMiLL5** [comment]
I made a local fix for this in `_processNodeFormat`,

Change
`while (node && !$(node).is('.fr-marker') && $(node).find('.fr-marker').length == 0) {`
To
`while ( node && !$( node ).is( '.fr-marker, a, ul, ol, li' ) && $( node ).find( '.fr-marker' ).length == 0 ) {`

And 
`else if ($(node).find('.fr-marker').length) {`
To
`else if ($(node).find('.fr-marker').length || $( node ).is( 'a, ul, ol, li' )) {`

This fix also addressed #1739

**Comment by stefanneculai** [comment]
This is behaving incorrectly by wrapping the `LI` in a span actually. I marked this as an enhancement and we'll review it.

**Comment by stefanneculai** [comment]
This has been fixed in a recent commit on master.

**Comment by GMiLL5** [comment]
@stefanneculai Just got around to testing this in 2.5.0 & it looks like it's still an issue

The steps are fairly similar, just need to have another element in the editor as well (I was triggering with an additional empty <p> tag)

`<ul><li>test<ul><li>test</li></ul></li></ul><p><br></p>` Use that as the editor content & try cmd+a then apply a style
