### ISSUE TITLE
Copy-paste source is being included in master

### ISSUE THREAD

**Issue by jeremylynch** [froala/wysiwyg-editor#1883]
[Clinical Anatomy 11th ed samoke.pdf](https://github.com/froala/wysiwyg-editor/files/890099/Clinical.Anatomy.11th.ed.samoke.pdf)

Copy & paste from the document above. The documents source/title will be included at the start of the pasted content (master version only).

**Comment by stefanneculai** [comment]
As a clarification, the document should be opened with Preview on MacOS.

**Comment by stefanneculai** [comment]
Should be fixed on the current master.

**Comment by jeremylynch** [comment]
@stefanneculai this is still not fixed. Please try the following PDF document (in Preview on Mac only): 

http://che.org.il/wp-content/uploads/2016/12/pdf-sample.pdf

**Comment by stefanneculai** [comment]
@jeremylynch we've tried to reproduce it without success. Could you please make a recording?

**Comment by jeremylynch** [comment]
I will make a recording, have you tried the div-enter setting?

**Comment by jeremylynch** [comment]
@stefanneculai have you had the chance to review this?

**Comment by jeremylynch** [comment]
![ezgif com-video-to-gif 17](https://cloud.githubusercontent.com/assets/3665457/25665669/a30fbf4a-3061-11e7-9641-4d13d15d9683.gif)

**Comment by stefanneculai** [comment]
Yes, we cannot reproduce it on master.

**Comment by jeremylynch** [comment]
Could you please provide the master CDN so I can reproduce it in a JS fiddle ?

**Comment by jeremylynch** [comment]
@stefanneculai this is still occurring in master (`2.6.0`). 
I have finally worked out what is causing this: 
The code in question is below
```
  editors.on('froalaEditor.paste.beforeCleanup', function (e, editor, clipboard_html) {
    html = clipboard_html
    $html = $('<div />',{html:html});
    $html.find('*').css('font-family', '')
    return $html.html()
  });
```
