### ISSUE TITLE
Updating to v2.6 froalaEditor.drop stops firing

### ISSUE THREAD

**Issue by ghedwards** [froala/wysiwyg-editor#1961]
I updated to v2.6 ( from 2.5 ) and my froalaEditor.drop events stopped firing. Prior to the update the below code runs correctly.

.on('froalaEditor.drop', function(e, editor, dropEvent) {

**Comment by stefanneculai** [comment]
Please use it like this so that it gets triggered before other editor events:

```js
$('selector').on('froalaEditor.initialized', function (e, editor) {
  editor.events.on('drop', function () {
  }, true);
}).froalaEditor();

**Comment by ghedwards** [comment]
So I guess then you should update your Drop Content Demo code, and your API documentation ? It seems like the issue you've "closed" are breaking changes ?
https://www.froala.com/wysiwyg-editor/examples/drop-content
https://www.froala.com/wysiwyg-editor/docs/events#drop

**Comment by stefanneculai** [comment]
@ghedwards it's going to be updated on our website as well.

**Comment by ghedwards** [comment]
These breaking changes aren't mentioned in the release notes ?

**Comment by stefanneculai** [comment]
It is a side effect of an issue we fixed. We're going to make all the necessary corrections for it in docs in the following hours.

**Comment by tommybstitch** [comment]
As of 2.6.1 I'm still having this issue. Drop event is not firing using either method you describe @stefanneculai

**Comment by VickNet** [comment]
`froalaEditor.drop` nu va mai fi disponibil în următoarele actualizări?

**Comment by stefanneculai** [comment]
Please find details for binding to drop event here: https://www.froala.com/wysiwyg-editor/examples/drop-content
