### ISSUE TITLE
Extra spaces when htmlUntouched is true

### ISSUE THREAD

**Issue by dswitzer** [froala/wysiwyg-editor#2314]
##### Expected behavior.
Froala should not add extra spaces to content

##### Actual behavior.
Froala is adding extra spaces to content, when the `htmlUntouched: true` option is set. This happens when a text node has multiple spaces (`chr(32)`).

The problem appears to be due to the `_normalizeNode()` function in the `$.FE.MODULES.spaces` namespace. The problem appears to be around this line of code:

```
        if (txt.charCodeAt(t) == 32 && (t === 0 || new_text.charCodeAt(t - 1) == 32)) {
          new_text += $.FE.UNICODE_NBSP;
        }
```

If I set `$.FE.UNICODE_NBSP` to a normal space, everything works properly. 

The problem is that when you have 2 normal spaces, the `new_text` ends up seeing a space followed by a no breaking space, which makes the `node.textContent != new_text` comparison always fail. This causes the `node.textContent = new_text` line to execute, which ends up adding undesired spaces throughout the document.

If the `htmlUntouched: true` is true, it should not be altering the text at all. However, it seems like this would be leading to other bugs.

##### Steps to reproduce the problem.
I can get the issue to happen when I used the following file as the content of an editor under Firefox 56.0.2:

[froala_extra_spaces_issue_htm.txt](https://github.com/froala/wysiwyg-editor/files/1447929/froala_extra_spaces_issue_htm.txt)

In Chrome 62.0.3202.75, I need to add a space to the end of the second paragraph and then delete it to see the extra spaces.

##### OS.
Windows 10

##### Browser.
Firefox 56.0.2, Chrome 62.0.3202.75

**Comment by stefanneculai** [comment]
@dswitzer thanks for bringing this to our attention. We're going to check it.

**Comment by stefanneculai** [comment]
@dswitzer we just tested this and it appears to work correctly in version 2.7.2. Could you please check it and let us know your thoughts?

**Comment by dswitzer** [comment]
@stefanneculai 

There's still something odd going on. While extra spaces are not getting added, the extra spaces are showing. At first I thought it was a CSS issue, but the `white-space` setting seems to be set to `normal`.

Open the test froala_extra_spaces_issue_htm.txt document and look at the text. Then copy and paste it into the Froala Editer (https://www.froala.com/wysiwyg-editor/).

You'll see that each space in the code it's rendering a space—but multiple spaces should be collapsed.

You can see an example here. There are 2 spaces after each period. When you view the document normally, you only see a single space because the white space is properly collapsed. However, once it's pasted both white spaces show.

Each time I press the space bar another white space shows.

![multiple_spaces](https://user-images.githubusercontent.com/900497/33840865-1ed8573a-de64-11e7-86df-bf341758920b.gif)

**Comment by stefanneculai** [comment]
Should be fixed on the current master.

**Comment by dswitzer** [comment]
I'm still seeing this issue:

https://jsfiddle.net/dswitzer/c9xn3qe9/

If you place a space at the end of the first paragraph you can see the content really gets messed up. It's converted whitespace into &nbsp; that should never be getting converted.

The _normalizeNode() function in $.FE.MODULES.spaces is the root problem. Since it's based on a regex parser, it just does not correctly identify whitespace within a block/inline element.

I'm really not sure why it's trying to translate the spaces in the first place—it seems like it should be leaving them alone.

To resolve the problem, I changed the following line in _normalizeNode() from:
```
      if (editor.html.isPreformatted(parent_node)) return;
```

To:
```
      /* MOD */
      // Added the htmlUntouched check, to avoid issues where extra spaces are being incorrectly converted into nobreak spaces and
      // rendered as spaces
      if (editor.opts.htmlUntouched || editor.html.isPreformatted(parent_node)) return;
```

What's the idea behind the need for _normalizeNode()?

**Comment by stefanneculai** [comment]
@dswitzer could you please confirm that you have this problem in version 2.9.1? It looks good to me now. If you still see something incorrect, could you please make a recording?

**Comment by stefanneculai** [comment]
Hi @dswitzer! We have this for review in the current sprint. Do you think you could help us with confirming if it is working fine now? If not, maybe you could provide a recording? Thanks in advance.

**Comment by stefanneculai** [comment]
Closing this as per our checks the problem is no longer there in 2.9.1.
