### ISSUE TITLE
Changing text format in a contenteditable="true" element that is inside a contenteditable="false" element

### ISSUE THREAD

**Issue by Apee** [froala/wysiwyg-editor#2427]
##### Expected behavior.
We can change any option that is selectable **via a menu** in a contenteditable="true" zone that is inside a contenteditable="false" zone

##### Actual behavior.
When we mouse hover **an option that is selectable via a sub-menu**, we're loosing current selection and the selection goes a the start of the editor. So it's impossible to change option for given text in that context.

##### Steps to reproduce the problem.
I've created a plunker for it.
https://plnkr.co/edit/mZRsREb9lTr1VQByxas5?p=preview

**Comment by Apee** [comment]
Any development on that issue ?

**Comment by stefanneculai** [comment]
@Apee we're working on finding a workaround for it, however, we cannot provide an ETA for it yet.

**Comment by Apee** [comment]
Thank you ! :)

**Comment by petester42** [comment]
@stefanneculai just updated to the latest version 2.7.5 and this issue still happens. Here is a plunker with the version updated https://plnkr.co/edit/bsH8IxCDvZEseLrsSZwA

**Comment by stefanneculai** [comment]
@petester42 it is fixed. In the Plunker you sent, you updated only the CSS to 2.7.5, not the JS.

**Comment by petester42** [comment]
You are right it works with the JS updated. It still doesn’t seem to work right in our app after the update so it must be something else.
