### ISSUE TITLE
[IE] Font size is not applied on text

### ISSUE THREAD

**Issue by javeriaanwer** [froala/wysiwyg-editor#2445]
Hi, 
I try to change font size in IE but it didn't work only if I enable iframe.

1. Insert Some text.
2. Change font size

you can see this in following example: 
https://codepen.io/Javeria_Anwer/pen/wpWQPX

Browser:
Internet Explorer 11

**Comment by stefanneculai** [comment]
@javeriaanwer please upgrade to version 2.7.5.

**Comment by javeriaanwer** [comment]
thank you Stefan, I upgraded froala version but still this problem occurs.

https://codepen.io/Javeria_Anwer/pen/wpWQPX

Browser:
Internet Explorer 11

**Comment by stefanneculai** [comment]
@javeriaanwer this should be fixed in the current master version. Could you give it a try?

**Comment by javeriaanwer** [comment]
I tried updated version but issue still exists. We find that this error only occurs if webpage, which is containing editor, and editor itself are in iframe.  We cannot remove iframe from either one of them. 

You can also see this bug in “Code Pan” and “Js Fiddle”. 

Code Pan: https://codepen.io/Javeria_Anwer/pen/wpWQPX
Js Fiddle: http://jsfiddle.net/ubdmyoep/204/

**Comment by dianaprajescu** [comment]
Reopening this issues as it is still happening in the basic editor when `iframe` is `true`: https://jsfiddle.net/jfgqk3uL/

**Comment by stefanneculai** [comment]
Closing this as it should be fixed with the Github master
