### ISSUE TITLE
Custom popup plugins don't hide when clicking outside editor

### ISSUE THREAD

**Issue by wrporter** [froala/wysiwyg-editor#2531]
#### Steps to reproduce the problem.

jsFiddle: https://jsfiddle.net/wesleyrporter/1d0qay37/

1. Follow the docs on creating a custom plugin.
2. Click on the button to open the plugin
3. Click outside the editor

**Actual Behavior:** The popup does not hide

**Expected Behavior:** The popup should hide like other popups (link, video, image, file, etc)

##### OS.
macOS Sierra 10.12.6

##### Browser.
Chrome 63.0.3239.132

**Comment by dianaprajescu** [comment]
@wrporter this is already fixed in the latest version from the master branch of this repo.

**Comment by wrporter** [comment]
@dianaprajescu It looks like this is still an issue in some cases.

Steps to reproduce:

1. Click on any other built-in popup, such as link or color
2. Click on custom popup button (the star)
3. Click outside the editor

Result: The custom popup does not hide

Expected Result: The custom popup hides, just like other popups

**Comment by dianaprajescu** [comment]
Doesn't seem to happen in 2.7.5. Are you sure you updated the editor?

**Comment by wrporter** [comment]
Ah, it appears that that is only the case when using the `popup: true` option. I was told to use that option in a previous ticket. Removing it makes the popup hide as expected.
