### ISSUE TITLE
Table cell(s) copy/cut and paste not working as expected

### ISSUE THREAD

**Issue by codeabit** [froala/wysiwyg-editor#2701]
##### Expected behavior.
When table cells are selected (highlighted in blue) in the Froala editor and you use the keyboard to copy/cut (e.g. CMD/CTRL-C, CMD/CTRL-X) cells then when you paste (e.g. CMD/CTRL-V) the cells into a selection of the same size the cell contents should be the same and what was cut/copied.

##### Actual behavior.
Whatever happens to be in your clipboard is pasted into the last cell you have selected.

##### Steps to reproduce the problem.
Problem is reproduced in fiddle below.
https://jsfiddle.net/codeabit/0mvhe1bm/12/

##### OS.
OS X

##### Browser.
Chrome

**Comment by stefanneculai** [comment]
It is fixed on the current master.

**Comment by codeabit** [comment]
I just tested using the latest commit (771c2ecb4e0758f7c697ed0f2477ed7e1fe68dd9) and it still does not work for me. It still behaves the same as in the jsfiddle above.
