### ISSUE TITLE
OL and UL Buttons/Icons Missing

### ISSUE THREAD

**Issue by moses-bowman** [froala/wysiwyg-editor#3157]
##### Expected behavior.
Ordered and unordered list buttons should appear on the editor

##### Actual behavior.
Only down arrows are appearing
**Screenshot**: https://i.imgur.com/m1u0VKN.png

##### Steps to reproduce the problem.
1. There are two classes for each textarea. Their only difference is that one has an _autofocus_ option.
**jQuery code**: https://pastebin.com/hFvd6rq5
2. The first class is in a Bootstrap modal and the other one isn't
3. If I remove the first jQuery class selector, the icons/buttons will appear
4. It probably has something to do with the second instance of
`$(".class").froalaEditor();`

##### OS.
(OS name and version here)
Windows 10 Pro x64

##### Browser.
(Browser name an version here)
Chrome and Vivaldi

**Comment by stefanneculai** [comment]
@moses-bowman Do you think it would be possible to make a jsFiddle to highlight the problem? That would speed-up things a lot. Here is a basic jsFiddle you could use as a starting point: https://jsfiddle.net/froala/wc5c3jhk/.

**Comment by moses-bowman** [comment]
@stefanneculai 
Thank you for the pre-made jsFiddle. The same bug appears:

https://jsfiddle.net/spindog/wc5c3jhk/2059/

**Comment by philipstratford** [comment]
I'm not experiencing this exact behaviour but since upgrading to v2.9 I am having an issue with OL and UL buttons too. In the toolbar, the dropdown arrow buttons for the UL and OL buttons are full-width and separated from their parent buttons by too large a gap. I've attached a screenshot to illustrate. This was taken whilst hovering the mouse cursor over the OL button.
![froala](https://user-images.githubusercontent.com/7631595/48363063-f6850700-e69c-11e8-8848-9c2fcd0d3684.PNG)

**Comment by tavosansal** [comment]
I am also experiencing this issue.

**Comment by stefanneculai** [comment]
It's fixed with the current master from Github.

**Comment by sChupin** [comment]
The issue described by @philipstratford is still occurring on version 2.9.1 with custom theme generated from customize tool (https://www.froala.com/wysiwyg-editor/customize)
See my issue: https://github.com/froala/wysiwyg-editor/issues/3169

**Comment by sChupin** [comment]
It's working correctly now, thank you

**Comment by Argorate** [comment]
same bug with 2.9.0, fixed by 2.9.1 thx !
