### ISSUE TITLE
[Word copy paste] font size for list is changed after pasting

### ISSUE THREAD

**Issue by waynechaw** [froala/wysiwyg-editor#3300]
##### Expected behavior.
font size should stay consistent
##### Actual behavior.
font gets smaller after pasting into froala

##### Steps to reproduce the problem.
Copy the word doc I have attached to this issue. Paste it into Froala.

<img width="955" alt="screen shot 2019-02-14 at 10 41 49 am" src="https://user-images.githubusercontent.com/7528925/52809643-990aa880-3045-11e9-8aca-633f2c954c0b.png">

![screen shot 2019-02-14 at 10 41 54 am](https://user-images.githubusercontent.com/7528925/52809641-990aa880-3045-11e9-9b9a-7da5660cb085.png)

word doc:
[listfontsize.docx](https://github.com/froala/wysiwyg-editor/files/2866398/listfontsize.docx)

I was able to produce the issue in Chrome on Mac 
This happens when you make the window width smaller. Font size for list is not copied over, so the browser's font-size css will be applied.

```
<ul>
<li><span style="font-family:&quot;Arial&quot;,sans-serif;color:black;">test</span></li>
<li><span style="font-family:&quot;Arial&quot;,sans-serif;color:black;">test</span></li>
<li><span style="font-family:&quot;Arial&quot;,sans-serif;color:black;">test</span></li>
</ul>
```

**Comment by ilyaskarim** [comment]
I put it on our bug list and someone will look over it shortly. I will get back to you as soon as we have news.

**Comment by stefanneculai** [comment]
@waynechaw This should be fixed on the current master. Do you think you could check it?

**Comment by waynechaw** [comment]
@stefanneculai how would I test it on the current master? i just tested it now on https://www.froala.com/wysiwyg-editor and the bug is still there

**Comment by waynechaw** [comment]
@stefanneculai 

I tested the master and saw a couple problems.

The font size for list is copied but the value of the font size is not consistent to how font size is converted for other elements. 
Using the word doc I attached as example, the paragraph and the list both have font size of 12 in Word. When copied into froala, the paragraph's font size is converted from 12 to 16px, but the list items font size is converted to 12.0pt.  Although when I inspect the html, the ul tag has 16px, but the li tag has 12.0pt.

Another issue is that there are 4 span tags nested in each li tags. It is not necessarily a bug but it might causes issues in the future.

Please see the attach screenshot 
![Screen Shot 2019-03-28 at 10 34 08 AM](https://user-images.githubusercontent.com/7528925/55180362-b2276e80-5146-11e9-9911-08ca0d94eee7.png)

I am testing this in Chrome on Mac

**Comment by stefanneculai** [comment]
@waynechaw these are the properties that we get when pasting from MSWord. Unfortunately, if it would be not to put that inline style, we'd run into other cases where the style wouldn't be pasted..

**Comment by waynechaw** [comment]
@stefanneculai if 12.0pt is coming from MSWord, is 16px also coming from MSWord? seems odd that the list would have both font size 16px and 12.0pt

**Comment by stefanneculai** [comment]
Yes, we are getting both of them in the HTML which is coming from Word, we are not doing any kind of such conversions.
