### ISSUE TITLE
Froala completely freezes after specific table cell selection

### ISSUE THREAD

**Issue by Krisell** [froala/wysiwyg-editor#3419]
##### Expected behavior.
The editor continues to work.

##### Actual behavior.
The editor completely freezes, with no other option than a reload.

##### Steps to reproduce the problem.
1. Use Safari (tested in the latest version)
2. Create a table with at least two cells.
3. Click and hold in one cell and drag to the other, then go back to first cell and release.
4. The toolbar stays disabled and the text is no longer editable.

##### OS.
macOS

##### Browser.
Safari 12

##### Recording.
![](https://firebasestorage.googleapis.com/v0/b/examnet-176208/o/froalaproblem.gif?alt=media&token=a6247d0d-61b1-40c9-a8e8-d10a30facfbb)

**Comment by Krisell** [comment]
This is perhaps the same issue as #2299 and #2169
The "quick clicking" which was hard to reproduce might have been accidentally doing what I show here.

**Comment by Krisell** [comment]
After some additional testing, I can confirm that the issue occurs in **all** browser, including latest Chrome and Firefox.

It is slightly harder to reproduce in Chrome and Firefox, and seem to require the selection of at least three cells, and some combination of fast movement. Safari seems to be completely deterministic and easy to reproduce, which should help with your debugging.

**Comment by Krisell** [comment]
The same problem remains in Froala 3 (the version on you landing page).

We're getting more and more reports from people who run in to this. How's the progress with the fix? Does anyone have any ideas about how to solve this by adding events or similar?

**Comment by navneetnagpal** [comment]
Fixed

**Comment by Krisell** [comment]
@navneetnagpal 
I'm afraid this issue remains in both 2.9.6 and latest v3 (verified on the example Froala-editor on your web page). It does seem to be a bit harder to make the issue appear, but I've managed multiple times now, in both Safari and Chrome.

Is this something you are aware of and working with, or would you like me to make a new recording of the steps I take (mostly random dragging and selecting cells)?

**Comment by Krisell** [comment]
I managed to find precise steps to reproduce this, in latest Chrome. I'm not sure if it was this easy before, or if your changes introduced this.

1. Click and hold on a cell.
2. Select another cell, and go back.
3. While still holding the mouse button down, move outside the editor.
4. Release the mouse button.
5. The editor is now completely frozen.

![](https://media.giphy.com/media/gjBmQB0HUcjYojHx6g/giphy.gif)

**Comment by Krisell** [comment]
@navneetnagpal This problem remains in the latest version, reproduced on the Froala website. Easier than ever to reproduce in Chrome. Froala is completely frozen after this.

![image](https://user-images.githubusercontent.com/25909128/120757492-e6f69380-c510-11eb-9235-cd6998b285ec.png)
