### ISSUE TITLE
TypeError: Cannot read property 'nextSibling' of undefined

### ISSUE THREAD

**Issue by vinaykevadia** [froala/wysiwyg-editor#3541]
##### Expected behavior.
Getting an error as shown below 
![image](https://user-images.githubusercontent.com/7442679/60862243-9a2db380-a23a-11e9-8069-b506e0f6d00c.png)

##### Steps to reproduce the problem.
Trying to integrate froala with grapesjs. 
Here is the froala initialization code: 
`// Froala  
              rte = $(el).froalaEditor({
                  toolbarContainer: '.gjs-pn-commands',
                  toolbarInline: true,
                  charCounterCount: false,
                  toolbarVisibleWithoutSelection: true
              });
              rte.froalaEditor('toolbar.show');`

Froala element is inside the iframe, as shown below : 
![image](https://user-images.githubusercontent.com/7442679/60862487-4e2f3e80-a23b-11e9-8626-8754b7ffcf47.png)

**Steps to reproduce the error:** 
Step1: When I first time selects text and click on the bold button to make it bold it is working fine. 
Step2: Focus out from froala text editor window. 
Step3: Again select text and click on Bold button, It will produce an error(Cannot read property 'nextSibling' of undefined) as mentioned above. 

##### Editor version.
Tried with version 2.9.5, and 3.0.2 as well.

##### OS.
Windows 10

##### Browser.
Chrome Version 75.0.3770.100 (Official Build) (64-bit), Windows

**Comment by casualuser** [comment]
Hi,

It looks like this may be related to `toolbarContainer: '.gjs-pn-commands'` option
At your screenshot I can't see any elements with class `.gjs-pn-commands` so this may be the case - Froala Editor just can't find that element.

Please create jsfidlle reproducing this issue and then we will be able to check this in details.

**Comment by vinaykevadia** [comment]
@casualuser .gjs-pn-commands element is there already, I can see toolbar visible on the page and I am able to click on toolbar buttons as well. let me create JS fiddle

**Comment by vinaykevadia** [comment]
@casualuser Please have a look at this fiddle.

**Comment by casualuser** [comment]
fixed in 3.0.3

**Comment by vinaykevadia** [comment]
@casualuser, Issue has not yet fixed. nothing is happening when I click on any toolbar button. 
Check out this fiddle https://jsfiddle.net/15ve23cs/9/

Double click text 'Hello world' and froala toolbar will appear, After that try to make some changes by clicking any toolbar button.

**Comment by vinaykevadia** [comment]
Got this error 
![image](https://user-images.githubusercontent.com/7442679/61263731-af10c680-a7a7-11e9-8f34-c2dfda0baf40.png)
