### ISSUE TITLE
vertical separator '-' does not work

### ISSUE THREAD

**Issue by SergeyKhval** [froala/wysiwyg-editor#3556]
##### Expected behavior.
Inserting '-' into toolbarButtons option creates a horizontal split point in toolbar

##### Actual behavior.
Toolbar does not split

##### Steps to reproduce the problem.
https://jsfiddle.net/g1Lht2df/

##### Editor version.
3.03

##### OS.
Ubuntu 19.04

##### Browser.
Latest chrome

**Comment by casualuser** [comment]
fixed in 3.0.4

**Comment by earshinov** [comment]
@SergeyKhval , Can you confirm that it works?

I forked the fiddle and updated Froala to 3.1.0, but it still doesn't work:
https://jsfiddle.net/earshinov/keywuqht/7/

```js
const editor = new FroalaEditor('#froala-editor', {
  toolbarButtons: [
    'fontSize', 'fontFamily',
    '-',
    'bold', 'italic', 'underline', 'strikeThrough',
  ]
})
```

![image](https://user-images.githubusercontent.com/52021/79271225-1d55f700-7ea8-11ea-90f1-da98dfc47491.png)

One can see that a "newline" element is inserted after the two button groups rather than between them:

![image](https://user-images.githubusercontent.com/52021/79271324-4b3b3b80-7ea8-11ea-932e-fb2cde15582c.png)

**Comment by earshinov** [comment]
Apparently one needs to wrap `toolbarButtons` into an extra array as demonstated here: https://jsfiddle.net/dejan_m/og0hxf2t/4317/.

```js
new FroalaEditor('#froala-editor',{
 toolbarButtons: [['fontSize', 'fontFamily','-', 'bold', 'italic', 'underline', 'strikeThrough']]
})
```
