### ISSUE TITLE
Type Error: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by flodlc** [froala/wysiwyg-editor#3582]
##### Actual behavior.
When I try to select a text color, I often get this error:
`Cannot read property 'getBoundingClientRect' of undefined`
It happens only with the option `toolbarContainer`. I tried to change the container but no way, the only way to stop getting this error is removing it.

The errors  is often followed by this one: 
`Cannot read property 'tagName' of undefined`

It seems that the editor is loosing the selection sometimes (also the fr-markers) which triggers some issues.

##### Editor version.
Froala 3.0.3

We have never seen this issue in the Froala Editor v2.*

##### OS.
Mac

##### Browser.
Chrome

**Comment by casualuser** [comment]
Hello,
This was recently fixed in 3.0.4 version released today. Please check if version 3.0.4 works well for you in this case.

**Comment by flodlc** [comment]
Unfortunately,  the same issue still exists in version 3.0.4. 
It happens only when I use two or more instances with the same toolbarContainer. 
When I first edit some text in the first `fr-view` it works, then I select some text in the other `fr-view` and it crashes.
Once it crashed, the background color and the insert-link tools are broken too (I have to reload the page). It could be related to the placement of the popups.

**Comment by flodlc** [comment]
Any updates about this issue? In some cases, selecting an image causes this Exception too.
Any help would be very appreciated. 
Thanks.

**Comment by laurentiusar** [comment]
Hi,

I have version 3.0.5 and still getting this error, when i try to editor.html.insert(varName).

**Comment by aureality** [comment]
I'm getting the same error when trying to use editor.html.insert()
![image](https://user-images.githubusercontent.com/723378/76862801-ea93f100-685e-11ea-98f0-58cdb96f3263.png)

**Comment by farahat80** [comment]
Same error here, guys there is a lot of issues all pointing to the same problem
https://github.com/froala/wysiwyg-editor/issues?q=is%3Aissue+is%3Aopen+getBoundingClientRect

most of these bugs have been open for more than 7 month

**Comment by johnny130** [comment]
I had this issue when I had a 'scrollableContainer' on my options that didn't match up with an element on the page. Removing that and/or fixing that resolved the issue.

**Comment by ilyaskarim** [comment]
We’re closing this issue due to inactivity. If you’re still experiencing this problem on the latest version of our editor, please feel free to reopen the issue and let us know. You can find details on the latest updates here: [Froala Editor Changelog](https://froala.com/wysiwyg-editor/changelog/).
