### ISSUE TITLE
JS error + duplicate text upon simple pasting of rich text content

### ISSUE THREAD

**Issue by philfreo** [froala/wysiwyg-editor#369]
1. On a Mac, open TextEdit and create a simple rich text document like this:
![screenshot 2015-01-05 10 30 25](https://cloud.githubusercontent.com/assets/97612/5617656/dd5af6e0-94c5-11e4-8c25-55733f03b478.png)

2. Copy that text

3. Open http://jsfiddle.net/mtb2vdqc/

4. Open your browser's console so you can see JS errors

5. Paste the copied rich text above the `--` line in the JS fiddle

ERROR: Uncaught InvalidNodeTypeError: Failed to execute 'setStartAfter' on 'Range': the given Node has no parent.

![screenshot 2015-01-05 10 32 59](https://cloud.githubusercontent.com/assets/97612/5617683/3a4d72ba-94c6-11e4-93eb-850328230f1b.png)

It only seems to happen if there's some existing text in the editor.

**Comment by stefanneculai** [comment]
Fixed cf0cfe2b0ff19edb5fdf2ed559a2df9fb8fa6b81

**Comment by philfreo** [comment]
This is way better than before now ( :+1: ) but I think there's a minor issue still.

When following the instructions above but pasting multiple times in a row instead of a single time -- the cursor appears on the next line however the pasted content is appearing above

![screenshot 2015-01-06 08 28 44](https://cloud.githubusercontent.com/assets/97612/5631781/1dc044b6-957e-11e4-8326-f8e8a09350ba.png)

**Comment by philfreo** [comment]
There's also a problem where the whitespace lines are duplicated. So if you paste this from a rich text mode of TextEdit:

> Hi there
> 
> Goodbye

Then you'll get two blank lines (plus the cursor problem)

![screenshot 2015-01-06 09 00 26](https://cloud.githubusercontent.com/assets/97612/5632302/78003798-9582-11e4-8686-bd52c38a78f3.png)

**Comment by stefanneculai** [comment]
See c8e65b1fa2ce61303862d55813a32d2adca24986

**Comment by philfreo** [comment]
:+1: 

When pasting the rich text now it's introducing `<p>` tags into the editor with `paragraphy: false`. I don't really mind this (I'm assuming TextEdit itself is copying `<p>` tags so Froala is keeping it), but just wanted to bring it up in case you missed it.

**Comment by stefanneculai** [comment]
We know about that, but this is what is pasted into the editor and we decided to leave it like this.

**Comment by philfreo** [comment]
:+1:
