### ISSUE TITLE
Method "setSelection" is not working

### ISSUE THREAD

**Issue by imktks** [froala/wysiwyg-editor#378]
Hello, 
i think that after version 1.2.2 the setSelection method is not working. I tried the versions 1.2.3, 1.2.4, 1.2.5 but no luck..Do you have any suggestion ? 
Thank you!

**Comment by stefanneculai** [comment]
What do you mean by is not working? We are using it in several places in editor and it works fine.

**Comment by imktks** [comment]
I am attempting to create a selection in order to add color on the selected text and nothing happens

**Comment by stefanneculai** [comment]
If can you make a jsFiddle to replicate it, then we'll check.

**Comment by imktks** [comment]
Here it is: http://jsfiddle.net/kvg6b53d/3/

**Comment by stefanneculai** [comment]
Indeed, it's an issue. We'll update shortly. Thanks for brining this into our attention.

**Comment by stefanneculai** [comment]
Fixed 78cfc87d2dd4e81f805d675f350351ac6ae79562

**Comment by KenStipek** [comment]
I believe this is still an issue with v1.2.8

http://jsfiddle.net/oLvndfo4/1/

**Comment by nick-hs** [comment]
I believe I am having same issue. 
setSelection doesn't appear to be working properly for me either.

**Comment by stefanneculai** [comment]
Yes it works: http://jsfiddle.net/oLvndfo4/2/.

**Comment by nick-hs** [comment]
Using your last link: http://jsfiddle.net/oLvndfo4/2/

I tried in Firefox and it worked as expected.
I tried in Safari and it worked as expected.
I did not try with IE.

I tried in Chrome it did not work as expected. Froala didn't load in Chrome at all.
I'm using Chrome Version 43.0.2357.124 (64-bit)

**Comment by stefanneculai** [comment]
That's because you are not including the JS files correctly and jsFiddle is not loading them. http://jsfiddle.net/oLvndfo4/3/

**Comment by nick-hs** [comment]
That was a link you provided. I did not create the jsfiddle.

The last link you provided does work! Thank you! :smile:

**Comment by KenStipek** [comment]
OK, so the [documentation](https://www.froala.com/wysiwyg-editor/docs/methods#setSelection) needs to updated? As this fiddle works when using:
```
$('#edit').editable("setSelection", node.get(0).childNodes[0], 5, node.get(0).childNodes[0], 10);
```
But not:
```
$('#edit').editable("setSelection", node.get(0), 5, node.get(0), 10);
```
Like the documentation states?

**Comment by stefanneculai** [comment]
No, the documentation is correct. `sn` is the start node and `so` is the start offset node inside the node. If you have `<span id="sn">12<span>3</span>45</span>` and use `sn = $('#sn').get(0)` then `so=1` will be the `span` inner span. http://jsfiddle.net/oLvndfo4/5/

In the jsFiddle you created there is only one node inside the `<p>` tag if you want to select text you have to use the text node inside it.

**Comment by KenStipek** [comment]
Alright, cool. thanks

**Comment by nick-hs** [comment]
Thanks for the quick responses @stefanneculai ! It's much appreciated!
