### ISSUE TITLE
Copy pasting HTML table inside froala editor for second time breaks the Editor

### ISSUE THREAD

**Issue by Prince-Devadoss** [froala/wysiwyg-editor#3882]
##### Expected behavior.
Copy pasting table inside froala editor for second time should happen.
After pasting table should be visible inside editor.

##### Actual behavior.
Copy pasting table inside froala editor for second time breaks Editor.
Creates vertical line instead of table content.

##### Steps to reproduce the problem.
Copy the html table and paste it inside froala editor.
Try doing the same for second time without page refresh breaks the editor.

##### Editor version.
v3.0.6

##### OS.
MAC mojave

##### Browser.
Google Chrome Version 73.0.3683.103

##### Recording.

![issue](https://user-images.githubusercontent.com/57701834/79745890-b95b8480-8326-11ea-90dd-c5d967c8cb78.gif)

**Comment by earshinov** [comment]
There are no clear repro steps in the description, but I guess this issue is fixed as well as the related #3912

**Comment by Vignesh-Manogar-E3433** [comment]
https://github.com/froala/wysiwyg-editor/issues/3912 still exists in Safari browser.

**Comment by ilyaskarim** [comment]
We’re closing this issue due to inactivity. If you’re still experiencing this problem on the latest version of our editor, please feel free to reopen the issue and let us know. You can find details on the latest updates here: [Froala Editor Changelog](https://froala.com/wysiwyg-editor/changelog/).
