### ISSUE TITLE
Using <br> line break mode causes text to be lost in iOS

### ISSUE THREAD

**Issue by shff** [froala/wysiwyg-editor#4032]
##### Expected behavior.

I expected the editor not to lose the text.

##### Actual behavior.

After hitting "return" twice the editor 

##### Steps to reproduce the problem.

 - Open Safari on iPhone or iOS Simulator
 - Go to https://froala.com/wysiwyg-editor/examples/enter/ 
 - Type "Hello"
 - Hit enter twice

##### Editor version.

3.1.0 onwards

##### OS

iOS 13

##### Browser

Safari

##### Recording

![ezgif-6-64c9a9935cea](https://user-images.githubusercontent.com/25377830/92654840-bae71280-f2f0-11ea-88e8-bde09dc749e8.gif)

**Comment by mpvader** [comment]
Hi, we’re having this exact issue. Is there a time line for a fix?

**Comment by mpvader** [comment]
Hi, again, could it be that this is solved? In the demo linked above, I cannot reproduce it on any of the three demos.

While on our own use of Froala, an installation of Devada Answerhub, the problem does occur. Its utterly frustrating.

Answerhub support is looking into it, but not making any progress at all, and is, per this issue, blaming Froala and saying its out of their hands.

**Comment by burtonrhodes** [comment]
This issue is still occurring using the most current version.  It is very frustrating for my users.

**Comment by burtonrhodes** [comment]
I stand corrected.  It appears our implementation is now working correctly.  We are using v4.0.8 with options 
`{enter: FroalaEditor.ENTER_BR}`
