### ISSUE TITLE
editor.events.focus() and autofocus doesn't work in Chrome and Safari.

### ISSUE THREAD

**Issue by bjornri** [froala/wysiwyg-editor#4144]
##### Expected behavior.
The editor should be focused with blinking cursor.

##### Actual behavior.
Nothing happens.

##### Steps to reproduce the problem.
Use this fiddle: https://jsfiddle.net/8rup537f/
Setting autofocus: true causes the editor to get focused in Firefox - but not Chrome and Safari.
Clicking the focus button which calls editor.events.focus() focuses the editor in Firefox - but not Chrome and Safari.

##### Editor version.
3.2.5-1

##### OS.
Mac / Windows

##### Browser.
Chrome 87.0.4280.141 / MS Edge 87.0.664.75 / Safari 14.0.2

**Comment by mikesul** [comment]
Though I haven't explicitly tested it, I suspect the underlying issue is what I reported in #4099 (meaning that the underlying `focus` method is never triggered on the editor element).

**Comment by dejanmartinovic** [comment]
@bjornri the issue is solved in version 3.2.5-2

**Comment by bjornri** [comment]
https://jsfiddle.net/opa9wehx/ - This is the same fiddle, but with 3.2.5-2. Sadly the issue still occur.

I also tried 3.2.6 in the hopes that this release would fix it, but it doesn't look like it did but nor do the changelog say so (https://jsfiddle.net/opa9wehx/1/).

**Comment by dejanmartinovic** [comment]
@bjornri I agree. It's not working with jsFiddle. However, if you open the HTML file or run the editor on localhost it works as expected. You can also test the demos on the website https://froala.com/wysiwyg-editor/examples/. Click on the toolbar button should focus the editor.

**Comment by ilyaskarim** [comment]
We’re closing this issue due to inactivity. If you’re still experiencing this problem on the latest version of our editor, please feel free to reopen the issue and let us know. You can find details on the latest updates here: [Froala Editor Changelog](https://froala.com/wysiwyg-editor/changelog/).
