### ISSUE TITLE
Hitting enter in table scrolls to top when there is a lot of content

### ISSUE THREAD

**Issue by codemzy** [froala/wysiwyg-editor#4149]
##### Expected behavior.
Enter should just insert a new line in table cell

##### Actual behavior.
Enter inserts new line but can also scroll the page to the top

##### Steps to reproduce the problem.
Create a lot of content, add a table with multiple columns and rows, start adding content.

##### Editor version.
3.2.5+ (since the `Fixed The editor scrolls down if contains a lot of content` issue was fixed maybe?)

##### OS.
Mac

##### Browser.
Chrome

##### Recording.

https://user-images.githubusercontent.com/13764272/105165091-ce5f8100-5b0d-11eb-931b-325703531dc6.mp4

**Comment by thabrlawrenz** [comment]
I get the same issue. For me when I add about 5 lines of text (with about 20 words each). Then I press enter again, it will scroll to the top.

**Comment by alexanderkenney** [comment]
We're having exactly the same problem. If the return key is pressed when in a table, you are scrolled back to the top of the screen. Interestingly the cursor is still positioned within the table, because if you simply type after this happens, you go back down to the table cell.

**Comment by simon-jouet** [comment]
We have the same exact issue with 3.2.6 even without tables looks to mostly happen when froala input reaches a certain height

**Comment by manttih** [comment]
Can confirm this happens even without tables on latest version (3.2.6). I have inline editor, and heightMax : "auto".

**Comment by HiHub-Online** [comment]
Can anyone link this issue to https://github.com/froala/wysiwyg-editor/issues/3677

In one of the updates, I saw that the problem was resolved.
And happily closed the internal bugtrack after checking.
It's sad that it has to be reopened

**Comment by alexanderkenney** [comment]
Adding the following for anyone with this issue. This is how we resolved the problem.

For us it was a combination of problems. We use a Sticky Toolbar and needed to fix the return key issue within a table (this problem). 

If we set a height for the editor in CSS, it resolved the Hitting Enter issue from within a table. We had set this to 100vh. However, this caused the toolbar to disappear when scrolling passed the 100vh height. This happened for min-height and height css rules. The Froala javascript was setting a "fr-sticky-off" css rule on the scroll.

When we took away the min-height and height CSS rules, the toolbar worked as expected, but the enter from within a table issue reappeared. 

We were using a DIV element as the container for the Froala Editor. So we thought, what would happen if we used something else?

Turns out that changing the container to a TextArea fixes both the sticky toolbar and hitting enter issue. We also needed to remove any min-height or height CSS rules from the editor element.

We still need to do some digging to find out why this is the case, but it now works.

**Comment by simon-jouet** [comment]
Thanks @alexanderkenney for the info, it worked fine. Just a word of caution though, I've opened #4223 but if you have `defaultWidth: 0` and `imageOutputSize: true` the uploaded images become very buggy. This issue is not a problem if you keep using a div for the container of froala. So at the moment you have to chose between an editor that jumps around when you type or one where the images uploaded are buggy...

**Comment by DavidAlban** [comment]
We've also got this issue. Similarly, we have the toolbar set to position: sticky with our own CSS. Only seems to happen on pages with tall tables. Think it might be to do with cells that have bullet points, though not 100% sure on that. Haven't got a fix as we can't use a textarea as we first display the editable content as read-only, then optionally switch to edit mode. We're on 3.2.6 and I'm seeing this in Edge/Chromium.

**Comment by bbeda** [comment]
Any idea when this is going to be sorted? This is causing us issues with clients being very annoyed by the problem!

**Comment by shnigi** [comment]
I have similar problem with a custom plugin. When I click certain element inside the editor then the click event is not triggered at all and Froala editor just scrolls to the top.

**Comment by arwinvdv** [comment]
@bbeda Froala support says next version 4.0.4 that should be release end of this month.

**Comment by jong-in-kim** [comment]
I have similar problem with a custom plugin. When I click certain element inside the editor then the click event is not triggered at all and Froala editor just scrolls to the top.

**Comment by ilyaskarim** [comment]
Fixed in 3.2.7: https://froala.com/wysiwyg-editor/changelog/#3.2.7

**Comment by MnichMaciej** [comment]
Hi. This issue with stickyToolbar and scrollableContainer still occurs. I checked Version 4.2.1, 4.2 and 4.1.4
