### ISSUE TITLE
Unable to backspace to remove <br> tags when `enter` option is set to `FroalaEditor.ENTER_BR`

### ISSUE THREAD

**Issue by m-andrew-albright** [froala/wysiwyg-editor#4187]
##### Expected behavior.
(Describe expected behaviour here)
- The editor should remove one BR when you backspace, then another when you backspace again

##### Actual behavior.
(Describe actual behaviour here)
- It is leaving two `<br>` tags as the "model" / text, and you cannot get rid of them without some finagling.

##### Steps to reproduce the problem.
(Describe the steps to reproduce the problem here. A [jsFiddle](https://jsfiddle.net/froala/wc5c3jhk/) is awesome when possible.)
- initialize a new froala editor like so:
```js
new FroalaEditor('#froala-editor-br', {
  enter: FroalaEditor.ENTER_BR
});
```
- press enter a couple times, then try to backspace to clear it out.
- or you can just go here to see it on jsfiddle: https://jsfiddle.net/f0mgrj7L/2/

##### Editor version.
If you don't know it, please see https://wysiwyg-editor.froala.help/hc/en-us/articles/360000717049-How-can-I-find-my-editor-version-.
- `3.2.6`

##### OS.
(OS name and version here)
- Affects all OS

##### Browser.
(Browser name an version here)
- Affects all browsers (Brave, Chrome, Firefox, Safari)

##### Recording.
(A recording showing how to reproduce the problem)
![CmiiwC31oZ](https://user-images.githubusercontent.com/4950445/110620528-b8aa2780-815e-11eb-9478-af01a0ba8315.gif)

**Comment by AkshayCM** [comment]
Thank you for your feedback. The request has been reported to the product management team for evaluation and consideration for an upcoming release.

**Comment by maximobesteiro** [comment]
Any update on a fix for this? This has been going on for far too much time. Do you have an estimated date?

**Comment by mightythomaspang** [comment]
Also looking for an update for this issue. Any chance we can expedite this one?

**Comment by ilyaskarim** [comment]
Fixed in V4.0.10: https://froala.com/wysiwyg-editor/changelog/

**Comment by maximobesteiro** [comment]
@ilyaskarim do you mean in version 4.0.12 (for what I see in the changelog)? I had already tried with version 4.0.10 and it was not fixed there.
