### ISSUE TITLE
Colon inside of a link gets double encoded

### ISSUE THREAD

**Issue by joeworkman** [froala/wysiwyg-editor#4887]
If I add a colon inside of a link, it will get double encoded. Example: 

```
/archives/?q=title:example
```

The above will get encoded to

```
/archives/?q=title%253Aexample
```

The reason for this is that a `:` is `%3a`. However, for some reason, the `%` inside of that is then getting encoded into `%25`. This results in the output becoming `%253A`

**Comment by markedmondson** [comment]
If you can host your own version of the link.js plugin, then this might fix it: https://temp.staticsave.com/67d377f381e55.js

It's version 4.3.0 with the `isEnabled()` fix from 4.5.0 added. The bug was introduced in 4.4.0 so this should solve the problem.

**Comment by MultinetVihe** [comment]
The bug still exists in version 4.5.2. I'm guessing that it's due to the link.js plugin running both the sanitizeURL function from froala, and encodeURI? https://cdn.jsdelivr.net/npm/froala-editor@4.5.2/js/plugins/link.min.js

Apparently 4.6.0 will fix https://github.com/froala/wysiwyg-editor/issues/4929 related to link encoding, so I'm hoping that they also took note of this issue and fix it

**Comment by zahidkarim24** [comment]
Fixed in V4.6: https://froala.com/wysiwyg-editor/changelog/#4.6
